"""
Drift detection for safety metrics.
"""

from dataclasses import dataclass
from datetime import datetime
from typing import Optional
from collections import deque


@dataclass
class DriftAlert:
    """Alert generated by drift detection."""
    metric: str
    current_value: float
    threshold: float
    trend: str  # increasing, decreasing, stable
    severity: str  # info, warning, critical
    message: str
    timestamp: str


class DriftMonitor:
    """
    Monitors safety metrics for drift and anomalies.

    Detects:
    - Threshold violations
    - Trend changes
    - Sudden spikes
    """

    def __init__(
        self,
        violation_rate_threshold: float = 0.10,
        erosion_slope_threshold: float = 0.15,
        latency_threshold_ms: float = 5000,
        window_size: int = 20
    ):
        self.violation_rate_threshold = violation_rate_threshold
        self.erosion_slope_threshold = erosion_slope_threshold
        self.latency_threshold_ms = latency_threshold_ms
        self.window_size = window_size

        # Historical tracking
        self.violation_history: deque = deque(maxlen=window_size)
        self.latency_history: deque = deque(maxlen=window_size)
        self.failure_turn_history: deque = deque(maxlen=window_size)

    def check(self, metrics: dict) -> Optional[DriftAlert]:
        """
        Check current metrics for drift.

        Returns alert if drift detected, None otherwise.
        """
        timestamp = datetime.now().isoformat()

        # Record history
        violation_rate = metrics.get('violation_rate', 0)
        self.violation_history.append(violation_rate)

        avg_latency = metrics.get('avg_latency_ms', 0)
        self.latency_history.append(avg_latency)

        failure_turn = metrics.get('avg_failure_turn')
        if failure_turn:
            self.failure_turn_history.append(failure_turn)

        # Check violation rate threshold
        if violation_rate > self.violation_rate_threshold:
            return DriftAlert(
                metric="violation_rate",
                current_value=violation_rate,
                threshold=self.violation_rate_threshold,
                trend=self._compute_trend(self.violation_history),
                severity="critical" if violation_rate > self.violation_rate_threshold * 1.5 else "warning",
                message=f"Violation rate ({violation_rate:.1%}) exceeds threshold ({self.violation_rate_threshold:.1%})",
                timestamp=timestamp
            )

        # Check latency threshold
        if avg_latency > self.latency_threshold_ms:
            return DriftAlert(
                metric="latency",
                current_value=avg_latency,
                threshold=self.latency_threshold_ms,
                trend=self._compute_trend(self.latency_history),
                severity="warning",
                message=f"Average latency ({avg_latency:.0f}ms) exceeds threshold ({self.latency_threshold_ms}ms)",
                timestamp=timestamp
            )

        # Check for erosion trend (failures happening earlier)
        if len(self.failure_turn_history) >= 5:
            erosion_slope = self._compute_slope(list(self.failure_turn_history))
            if erosion_slope < -self.erosion_slope_threshold:
                return DriftAlert(
                    metric="erosion_slope",
                    current_value=erosion_slope,
                    threshold=-self.erosion_slope_threshold,
                    trend="decreasing",
                    severity="warning",
                    message=f"Failures occurring earlier in trajectories (slope: {erosion_slope:.3f})",
                    timestamp=timestamp
                )

        # Check for sudden spike in violation rate
        if len(self.violation_history) >= 3:
            recent_avg = sum(list(self.violation_history)[-3:]) / 3
            historical_avg = sum(self.violation_history) / len(self.violation_history)
            if recent_avg > historical_avg * 1.5 and recent_avg > 0.05:
                return DriftAlert(
                    metric="violation_spike",
                    current_value=recent_avg,
                    threshold=historical_avg * 1.5,
                    trend="increasing",
                    severity="warning",
                    message="Sudden increase in violation rate detected",
                    timestamp=timestamp
                )

        return None

    def _compute_trend(self, history: deque) -> str:
        """Compute trend direction from history."""
        if len(history) < 3:
            return "stable"

        recent = list(history)[-3:]
        older = list(history)[:-3] if len(history) > 3 else recent

        recent_avg = sum(recent) / len(recent)
        older_avg = sum(older) / len(older) if older else recent_avg

        if recent_avg > older_avg * 1.1:
            return "increasing"
        elif recent_avg < older_avg * 0.9:
            return "decreasing"
        else:
            return "stable"

    def _compute_slope(self, values: list) -> float:
        """Compute simple linear slope."""
        if len(values) < 2:
            return 0.0

        n = len(values)
        x_mean = (n - 1) / 2
        y_mean = sum(values) / n

        numerator = sum((i - x_mean) * (y - y_mean) for i, y in enumerate(values))
        denominator = sum((i - x_mean) ** 2 for i in range(n))

        if denominator == 0:
            return 0.0

        return numerator / denominator

    def get_status(self) -> dict:
        """Get current monitoring status."""
        return {
            'violation_history_len': len(self.violation_history),
            'latency_history_len': len(self.latency_history),
            'current_violation_trend': self._compute_trend(self.violation_history),
            'current_latency_trend': self._compute_trend(self.latency_history)
        }
